# Generated by Django 2.2.3 on 2019-07-24 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('about', models.TextField(blank=True, verbose_name='Sobre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Cardapio',
                'verbose_name_plural': 'Cardapios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lojas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('about', models.TextField(blank=True, verbose_name='Sobre')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de adesão')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualiza em')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images', verbose_name='Imagem')),
                ('user_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojaadm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False, verbose_name='Pedido')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('id_loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='lojas.Lojas')),
                ('id_prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='lojas.Cardapio')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['id_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comanda', models.IntegerField(default=0)),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('total_comanda', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.IntegerField(default=0, verbose_name='Status')),
                ('user_view', models.IntegerField(default=0, verbose_name='Status')),
                ('id_loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comanda', to='lojas.Lojas')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comanda', to='lojas.Pedido')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comanda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'ordering': ['id_loja'],
            },
        ),
        migrations.AddField(
            model_name='cardapio',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardapio', to='lojas.Lojas'),
        ),
    ]
