# Generated by Django 2.2.3 on 2019-07-24 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lojas',
            name='user_admin',
        ),
        migrations.AddField(
            model_name='lojas',
            name='useradmin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lojaadm', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
